--------------------------------------------------------
-- Archivo creado  - viernes-mayo-10-2019   
--------------------------------------------------------
DROP TABLE "CO_GNC"."D_ENFERMEDAD" cascade constraints;
DROP TABLE "CO_GNC"."DT_ENFERMEDAD" cascade constraints;
DROP TABLE "CO_GNC"."D_TERNERA" cascade constraints;
DROP TABLE "CO_GNC"."DT_TERNERA" cascade constraints;
DROP TABLE "CO_GNC"."DT_TIEMPO" cascade constraints;
DROP TABLE "CO_GNC"."H_TERN_ENF" cascade constraints;
DROP TABLE "CO_GNC"."HT_TERN_ENF" cascade constraints;
DROP TABLE "CO_GNC"."ODS_D_ENFERMEDAD" cascade constraints;
DROP TABLE "CO_GNC"."ODS_D_TERNERA" cascade constraints;
DROP TABLE "CO_GNC"."ODS_H_TERN_ENF" cascade constraints;
DROP SYNONYM "PUBLIC"."DUAL";
DROP DATABASE LINK "CO_GNC"."DBL_COGNC";
DROP SEQUENCE "CO_GNC"."SEQ_ENFERMEDAD";
DROP SEQUENCE "CO_GNC"."SEQ_TERNERA";
DROP VIEW "CO_GNC"."V_CONTROL_D_ENFERMEDAD";
DROP VIEW "CO_GNC"."V_CONTROL_D_TERNERA";
DROP PROCEDURE "CO_GNC"."P_DWH_DT_ENFERMEDAD";
DROP PROCEDURE "CO_GNC"."P_DWH_DT_TERNERA";
DROP PROCEDURE "CO_GNC"."P_DWT_DT_TIEMPO";
DROP PROCEDURE "CO_GNC"."P_HT_TERN_ENF";
DROP PROCEDURE "CO_GNC"."P_ODS_D_ENFEREDAD";
DROP PROCEDURE "CO_GNC"."P_ODS_D_TERNERA";
DROP PROCEDURE "CO_GNC"."P_ODS_H_TERN_ENF";
--------------------------------------------------------
--  DDL for DB Link DBL_COGNC
--------------------------------------------------------

  CREATE DATABASE LINK "DBL_COGNC"
   CONNECT TO "TAMBO" IDENTIFIED BY VALUES '05BAC15BF5DA7314978067FCC609001DFD'
   USING 'localhost:1521/xe';
--------------------------------------------------------
--  DDL for Sequence SEQ_ENFERMEDAD
--------------------------------------------------------

   CREATE SEQUENCE  "CO_GNC"."SEQ_ENFERMEDAD"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TERNERA
--------------------------------------------------------

   CREATE SEQUENCE  "CO_GNC"."SEQ_TERNERA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table D_ENFERMEDAD
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."D_ENFERMEDAD" 
   (	"ENFERMEDAD" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DT_ENFERMEDAD
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."DT_ENFERMEDAD" 
   (	"SK_ENFERMEDAD" NUMBER(*,0), 
	"PK_ENFERMEDAD" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table D_TERNERA
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."D_TERNERA" 
   (	"TERNERA" NUMBER(11,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE) DEFAULT 'Nro de carabana'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DT_TERNERA
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."DT_TERNERA" 
   (	"SK_TERNERA" NUMBER(*,0), 
	"PK_TERNERA" VARCHAR2(40 BYTE), 
	"DES_TER" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DT_TIEMPO
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."DT_TIEMPO" 
   (	"SK_TIEMPO" NUMBER(*,0), 
	"FECHA" DATE, 
	"ANIO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table H_TERN_ENF
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."H_TERN_ENF" 
   (	"TERNERA" NUMBER(11,0), 
	"ENFERMEDAD" VARCHAR2(30 BYTE), 
	"FECH_DESDE" DATE, 
	"FECH_HASTA" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HT_TERN_ENF
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."HT_TERN_ENF" 
   (	"SK_ENFERMEDAD" NUMBER(*,0), 
	"SK_TERNERA" NUMBER(*,0), 
	"SK_TIEMPO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"ALTA_USUARIO" VARCHAR2(50 BYTE), 
	"ALTER_FECHA" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ODS_D_ENFERMEDAD
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."ODS_D_ENFERMEDAD" 
   (	"ENFERMEDAD_PK" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ODS_D_TERNERA
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."ODS_D_TERNERA" 
   (	"TERNERA_PK" VARCHAR2(40 BYTE), 
	"DESC_TERNERA" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ODS_H_TERN_ENF
--------------------------------------------------------

  CREATE TABLE "CO_GNC"."ODS_H_TERN_ENF" 
   (	"TERNERA" NUMBER(11,0), 
	"ENFERMEDAD" VARCHAR2(40 BYTE), 
	"FECHA_DESDE" NUMBER(*,0), 
	"FECHA_HASTA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View V_CONTROL_D_ENFERMEDAD
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "CO_GNC"."V_CONTROL_D_ENFERMEDAD" ("ENFERMEDAD") AS 
  SELECT DISTINCT ENFERMEDAD
FROM H_TERN_ENF
WHERE
NOT EXISTS
 (
 SELECT  1
 FROM    D_ENFERMEDAD
 	WHERE   UPPER (H_TERN_ENF.ENFERMEDAD)=UPPER(D_ENFERMEDAD.ENFERMEDAD)
 );
--------------------------------------------------------
--  DDL for View V_CONTROL_D_TERNERA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "CO_GNC"."V_CONTROL_D_TERNERA" ("TERNERA") AS 
  SELECT DISTINCT TERNERA
FROM H_TERN_ENF
WHERE
EXISTS
 (
 SELECT  1
 FROM    D_TERNERA
 	WHERE   UPPER (H_TERN_ENF.TERNERA)=UPPER(D_TERNERA.TERNERA)
 );
--------------------------------------------------------
--  DDL for Index DT_ENFERMEDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CO_GNC"."DT_ENFERMEDAD_PK" ON "CO_GNC"."DT_ENFERMEDAD" ("SK_ENFERMEDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DT_SKTERNERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CO_GNC"."DT_SKTERNERA_PK" ON "CO_GNC"."DT_TERNERA" ("SK_TERNERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DT_SKTIEMPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CO_GNC"."DT_SKTIEMPO_PK" ON "CO_GNC"."DT_TIEMPO" ("SK_TIEMPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HT_TERN_ENF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CO_GNC"."HT_TERN_ENF_PK" ON "CO_GNC"."HT_TERN_ENF" ("SK_ENFERMEDAD", "SK_TERNERA", "SK_TIEMPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C005677
--------------------------------------------------------

  CREATE UNIQUE INDEX "CO_GNC"."SYS_C005677" ON "CO_GNC"."ODS_D_ENFERMEDAD" ("ENFERMEDAD_PK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DT_ENFERMEDAD
--------------------------------------------------------

  ALTER TABLE "CO_GNC"."DT_ENFERMEDAD" ADD CONSTRAINT "DT_ENFERMEDADSK_PK" PRIMARY KEY ("SK_ENFERMEDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CO_GNC"."DT_ENFERMEDAD" MODIFY ("SK_ENFERMEDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DT_TERNERA
--------------------------------------------------------

  ALTER TABLE "CO_GNC"."DT_TERNERA" ADD CONSTRAINT "DT_SKTERNERA_PK" PRIMARY KEY ("SK_TERNERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CO_GNC"."DT_TERNERA" MODIFY ("SK_TERNERA" NOT NULL ENABLE);
 
  ALTER TABLE "CO_GNC"."DT_TERNERA" MODIFY ("PK_TERNERA" NOT NULL ENABLE);
 
  ALTER TABLE "CO_GNC"."DT_TERNERA" MODIFY ("DES_TER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DT_TIEMPO
--------------------------------------------------------

  ALTER TABLE "CO_GNC"."DT_TIEMPO" ADD CONSTRAINT "DT_SKTIEMPO_PK" PRIMARY KEY ("SK_TIEMPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CO_GNC"."DT_TIEMPO" MODIFY ("SK_TIEMPO" NOT NULL ENABLE);
 
  ALTER TABLE "CO_GNC"."DT_TIEMPO" MODIFY ("FECHA" NOT NULL ENABLE);
 
  ALTER TABLE "CO_GNC"."DT_TIEMPO" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HT_TERN_ENF
--------------------------------------------------------

  ALTER TABLE "CO_GNC"."HT_TERN_ENF" ADD CONSTRAINT "HT_TERN_ENF_PK" PRIMARY KEY ("SK_ENFERMEDAD", "SK_TERNERA", "SK_TIEMPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CO_GNC"."HT_TERN_ENF" MODIFY ("SK_ENFERMEDAD" NOT NULL ENABLE);
 
  ALTER TABLE "CO_GNC"."HT_TERN_ENF" MODIFY ("SK_TERNERA" NOT NULL ENABLE);
 
  ALTER TABLE "CO_GNC"."HT_TERN_ENF" MODIFY ("SK_TIEMPO" NOT NULL ENABLE);
 
  ALTER TABLE "CO_GNC"."HT_TERN_ENF" MODIFY ("CANTIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ODS_D_ENFERMEDAD
--------------------------------------------------------

  ALTER TABLE "CO_GNC"."ODS_D_ENFERMEDAD" ADD UNIQUE ("ENFERMEDAD_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HT_TERN_ENF
--------------------------------------------------------

  ALTER TABLE "CO_GNC"."HT_TERN_ENF" ADD CONSTRAINT "HT_TERN_ENF_DTENF_FK1" FOREIGN KEY ("SK_ENFERMEDAD")
	  REFERENCES "CO_GNC"."DT_ENFERMEDAD" ("SK_ENFERMEDAD") ENABLE;
 
  ALTER TABLE "CO_GNC"."HT_TERN_ENF" ADD CONSTRAINT "HT_TERN_ENF_DTTERN_FK1" FOREIGN KEY ("SK_TERNERA")
	  REFERENCES "CO_GNC"."DT_TERNERA" ("SK_TERNERA") ENABLE;
 
  ALTER TABLE "CO_GNC"."HT_TERN_ENF" ADD CONSTRAINT "HT_TERN_ENF_DTTIEMPO_FK1" FOREIGN KEY ("SK_TIEMPO")
	  REFERENCES "CO_GNC"."DT_TIEMPO" ("SK_TIEMPO") ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_AUD_HT_TERN_ENF
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CO_GNC"."T_AUD_HT_TERN_ENF" 
BEFORE INSERT OR UPDATE
ON HT_TERN_ENF
FOR EACH ROW
BEGIN
SELECT USER,
	               SYSDATE
	INTO      :NEW.ALTA_USUARIO,
	               :NEW.ALTER_FECHA
	FROM    DUAL;
END T_AUD_HT_TERN_ENF;
/
ALTER TRIGGER "CO_GNC"."T_AUD_HT_TERN_ENF" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_ENFERMEDAD_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CO_GNC"."T_ENFERMEDAD_SEQ" 
BEFORE INSERT
ON DT_ENFERMEDAD
FOR EACH ROW
BEGIN
SELECT SEQ_ENFERMEDAD.NEXTVAL
INTO :NEW.SK_ENFERMEDAD
FROM DUAL;
END T_ENFERMEDAD_SEQ;
/
ALTER TRIGGER "CO_GNC"."T_ENFERMEDAD_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_TERNERA_SEQ
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CO_GNC"."T_TERNERA_SEQ" 
BEFORE INSERT
ON DT_TERNERA
FOR EACH ROW
BEGIN
SELECT SEQ_TERNERA.NEXTVAL
INTO :NEW.SK_TERNERA
FROM DUAL;
END T_TERNERA_SEQ;
/
ALTER TRIGGER "CO_GNC"."T_TERNERA_SEQ" ENABLE;
--------------------------------------------------------
--  DDL for Procedure P_DWH_DT_ENFERMEDAD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CO_GNC"."P_DWH_DT_ENFERMEDAD" 
IS
BEGIN
MERGE INTO DT_ENFERMEDAD a
USING (SELECT ENFERMEDAD_PK FROM ODS_D_ENFERMEDAD) o
ON (a.PK_ENFERMEDAD = o.ENFERMEDAD_PK)	
WHEN NOT MATCHED THEN
INSERT (PK_ENFERMEDAD)
VALUES
(o.ENFERMEDAD_PK)
;
COMMIT;
END P_DWH_DT_ENFERMEDAD;

/
--------------------------------------------------------
--  DDL for Procedure P_DWH_DT_TERNERA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CO_GNC"."P_DWH_DT_TERNERA" 
IS
BEGIN
MERGE INTO DT_TERNERA a
USING (SELECT TERNERA_PK,DESC_TERNERA FROM ODS_D_TERNERA) o
ON (a.PK_TERNERA = o.TERNERA_PK)	
WHEN NOT MATCHED THEN
INSERT (PK_TERNERA, DES_TER)
VALUES
(o.TERNERA_PK, o.DESC_TERNERA)
;
COMMIT;
END P_DWH_DT_TERNERA;

/
--------------------------------------------------------
--  DDL for Procedure P_DWT_DT_TIEMPO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CO_GNC"."P_DWT_DT_TIEMPO" 
is
FECHA_DESDE DATE;
FECHA_HASTA DATE;
BEGIN
FECHA_DESDE :=TO_DATE('20160101','YYYYMMDD');
FECHA_HASTA :=TO_DATE('20191230','YYYYMMDD');
WHILE FECHA_DESDE <= FECHA_HASTA
LOOP
INSERT INTO DT_TIEMPO
(SK_TIEMPO,FECHA,ANIO)
VALUES
(
TO_CHAR(FECHA_DESDE,'YYYYMMDD'),
FECHA_DESDE,
TO_CHAR(FECHA_DESDE,'YYYY')
);
FECHA_DESDE:=FECHA_DESDE+1;
END LOOP;
COMMIT ;
END P_DWT_DT_TIEMPO;

/
--------------------------------------------------------
--  DDL for Procedure P_HT_TERN_ENF
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CO_GNC"."P_HT_TERN_ENF" 
IS 
BEGIN
INSERT INTO HT_TERN_ENF
(SK_ENFERMEDAD,SK_TERNERA,
SK_TIEMPO,CANTIDAD
)
SELECT DT_ENFERMEDAD.SK_ENFERMEDAD,
DT_TERNERA.SK_TERNERA,
DT_TIEMPO.SK_TIEMPO,
1 CANTIDAD
FROM ODS_H_TERN_ENF
LEFT OUTER JOIN DT_ENFERMEDAD
ON DT_ENFERMEDAD.PK_ENFERMEDAD=ODS_H_TERN_ENF.ENFERMEDAD
LEFT OUTER JOIN DT_TERNERA
ON DT_TERNERA.PK_TERNERA=ODS_H_TERN_ENF.TERNERA
LEFT OUTER JOIN DT_TIEMPO
ON DT_TIEMPO.SK_TIEMPO=ODS_H_TERN_ENF.FECHA_DESDE;
COMMIT;
END P_HT_TERN_ENF;

/
--------------------------------------------------------
--  DDL for Procedure P_ODS_D_ENFEREDAD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CO_GNC"."P_ODS_D_ENFEREDAD" 
 	IS
 	BEGIN
 	DELETE FROM ODS_D_ENFERMEDAD;
 	INSERT INTO ODS_D_ENFERMEDAD
  SELECT 
  CASE 
    WHEN UPPER(TRIM(ENFERMEDAD))='NEUMONIA' THEN 'NEUMONÍA'
    WHEN UPPER(TRIM(ENFERMEDAD))='DIAREA' THEN 'DIARREA'
    ELSE UPPER(TRIM(ENFERMEDAD))
    END ENFERMEDAD
 	FROM D_ENFERMEDAD
 	;
 	COMMIT;
 END P_ODS_D_ENFEREDAD;

/
--------------------------------------------------------
--  DDL for Procedure P_ODS_D_TERNERA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CO_GNC"."P_ODS_D_TERNERA" 
 	IS
 	BEGIN
 	DELETE FROM ODS_D_TERNERA;
 	INSERT INTO ODS_D_TERNERA
 	( 
 	TERNERA_PK,
  DESC_TERNERA
  	)
 	SELECT UPPER(TRIM(TERNERA)),
  DESCRIPCION
 	FROM D_TERNERA
 	;
 	COMMIT;
  END P_ODS_D_TERNERA;

/
--------------------------------------------------------
--  DDL for Procedure P_ODS_H_TERN_ENF
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CO_GNC"."P_ODS_H_TERN_ENF" 
 	IS
 	BEGIN
 	DELETE FROM ODS_H_TERN_ENF;
 	INSERT INTO ODS_H_TERN_ENF
 	SELECT UPPER(TRIM(TERNERA)),
  case
   WHEN UPPER(TRIM(ENFERMEDAD))='NEUMONIA' THEN 'NEUMOÍA'
   WHEN UPPER(TRIM(ENFERMEDAD))='DIAREA' THEN 'DIARREA'
   ELSE UPPER(TRIM(ENFERMEDAD))
   END ENFERMEDAD,
  to_number(TO_CHAR(FECH_DESDE,'YYYYMMDD')),
  to_number(TO_CHAR(FECH_HASTA,'YYYYMMDD'))
 	FROM H_TERN_ENF
 	;
 	COMMIT;
  END P_ODS_H_TERN_ENF;

/
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
